from django.urls import path

from main.views import (show_main, 
                        show_experience, 
                        show_education, 
                        show_projects, 
                        create_project, 
                        get_projects_json,
                        get_education_json,
                        delete_project, 
                        show_experience_json,
                        show_edit_experience, 
                        create_experience, 
                        edit_experience, 
                        delete_experience,
                        show_edit_education,
                        create_education,
                        edit_education,
                        delete_education,
                        register,
                        login_user,
                        logout_user,
                        toggle_star,
                        edit_project,
                        create_project_ajax,
                        create_education_ajax,
                        toggle_star_education,
                        )
app_name = "main"

urlpatterns = [
    path("", show_main, name="show_main"),
    path("projects/add/", create_project, name="create_project"),
    
    path('projects/', show_projects, name='show_projects'),
    path("api/projects/", get_projects_json, name="get_projects_json"),
    path("projects/<uuid:project_id>/delete/",delete_project,name="delete_project"),
    path("projects/<uuid:project_id>/star/",toggle_star,name="toggle_star",),
    path("projects/<uuid:project_id>/edit/", edit_project, name="edit_project"), 
    path("projects/add-ajax/", create_project_ajax, name="create_project_ajax"), 

    path("experience/", show_experience, name="show_experience"),
    path("experience/edit/", show_edit_experience, name="show_edit_experience"),            
    path("experience/edit/form/", create_experience, name="create_experience"),             
    path("experience/edit/<uuid:experience_id>/form/", edit_experience, name="edit_experience"), 
    path("experience/delete/<uuid:experience_id>/", delete_experience, name="delete_experience"),
    path("experience/json/", show_experience_json, name="show_experience_json"),

    path('education/', show_education, name='show_education'),
    path('education/edit/', show_edit_education, name='show_edit_education'),
    path('education/create/', create_education, name='create_education'),
    path('education/edit/<uuid:education_id>/form/', edit_education, name='edit_education'),
    path('education/delete/<uuid:education_id>/', delete_education, name='delete_education'),
    path("api/education/", get_education_json, name="get_education_json"),
    path("education/add-ajax/", create_education_ajax, name="create_education_ajax"),
    path("education/<uuid:education_id>/star/", toggle_star_education, name="toggle_star_education"),

    path("register/", register, name="register"),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
]