"""
Django settings for myportofolio project.

Generated by 'django-admin startproject' using Django 6.1.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-7@&^womxrcfehev=hre5knyjecw+p5__sb#d=bn&^sft@u2+fh'

DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "rafael-darius-myportofolio.pws.cs.ui.ac.id", "*"]

PRODUCTION = os.getenv('PRODUCTION', 'False').lower() == 'true'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portofolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portofolio.wsgi.application'

if PRODUCTION:
    raw_port = os.getenv('DB_PORT', '5432')
    db_port = raw_port if (raw_port and raw_port.isdigit()) else '5432'

    raw_host = os.getenv('DB_HOST', '10.119.106.139').replace('<', '').replace('>', '').strip()
    db_host = '10.119.106.139' if (not raw_host or 'rafael' in raw_host) else raw_host

    raw_user = os.getenv('DB_USER', 'rafael.darius').strip()
    db_user = 'rafael.darius' if (raw_user == '10.119.106.139' or not raw_user) else raw_user

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'rafael.darius'),
            'USER': db_user,
            'PASSWORD': os.getenv('DB_PASSWORD', '4lc77JXZ'),
            'HOST': db_host,
            'PORT': db_port,
            'OPTIONS': {
                'options': f"-c search_path={os.getenv('SCHEMA', 'tutorial')}"
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# gunakan https:// untuk trailing urlnya
CSRF_TRUSTED_ORIGINS = ["https://rafael-darius-myportofolio.pws.cs.ui.ac.id/"]